### PR TITLE
Just aesthetic and more logical placement for restart.

### PR DESCRIPTION
**Pull request by Gontier-Julien**
Just aesthetic and more logical placement for restart variables, shouldn't be an issue what so ever.

Test on my mirror.

Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>

### CODE REVIEW

**Review by Technetium1 — APPROVED** [review]
LGTM

**Review by dr460nf1r3 — APPROVED** [review]

**Comment by dr460nf1r3** [comment]
Would you resolve the conflicts so we can have it merged? 😬

**Comment by Gontier-Julien** [comment]
Should be fine now!
Didn't see that git decided to keep the old `image: nginx` placement x)

**Comment by dr460nf1r3** [comment]
Thank you :)

**Pull request merged**
