### PR TITLE
Change to the official images for syncthing and nginx to the alpine images.

### PR DESCRIPTION
**Pull request by Gontier-Julien**
As discussed on the telegram group, we are switching nginx to the alpine images.
This make it more secure and more lite too.

I've also switch to official images for syncthing.

Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>

### CODE REVIEW

**Comment by Gontier-Julien** [comment]
I've tested on my mirror an everything went fine.
If just one or more person could test this just before we push this it would be great, and so we can be sure it 100% fine to do so.

**Review by Technetium1 — APPROVED** [review]
LGTM! Tests successfully on my x86 mirror, should be fine with aarch64.

**Review by dr460nf1r3 — APPROVED** [review]
👍

**Comment by JustTNE** [comment]
I'm switching back to normal nginx here because I hackily make chaotic-management reuse the nginx container.

**Pull request merged**
